# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('sobre_expansion', 'sobre_expansion'), ('lata', 'lata'), ('caja_ed_especial', 'caja_ed_especial'), ('sobre_duelista', 'sobre_duelista'), ('baraja_principiante', 'baraja_principiante'), ('baraja_estructura', 'baraja_estructura')], default='sobre_expansion', max_length=30)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
