# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='some'),
            preserve_default=False,
        ),
    ]
