# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, default='grupo/noimagen.jpg', help_text='Foto', null=True, upload_to='grupo/')),
                ('torneos_ganados', models.IntegerField()),
                ('duelistas', models.ManyToManyField(blank=True, default=None, null=True, to='jugador.Duelista')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
    ]
