# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0002_auto_20170819_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
