# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0003_auto_20170820_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='duelistas',
        ),
    ]
