# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
        ('grupo', '0004_remove_grupo_duelistas'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='duelistas',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='jugador.Duelista'),
        ),
    ]
