# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0005_grupo_duelistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='torneos_ganados',
            field=models.IntegerField(default=0),
        ),
    ]
