# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0006_auto_20170820_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
