# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0007_auto_20170820_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
