# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0008_auto_20170820_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='imagen',
            field=models.ImageField(blank=True, default='static/media/grupo/noimagen.jpg', help_text='Foto', null=True, upload_to='static/media/grupo/'),
        ),
    ]
