# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo_individual',
            name='numero_participantes_disponibles',
            field=models.IntegerField(default='00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torneo_individual',
            name='id_torneo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
