# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_auto_20170820_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo_individual',
            name='numero_participantes_disponibles',
        ),
        migrations.AlterField(
            model_name='torneo_individual',
            name='ganador',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='torneo_individual',
            name='id_torneo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
