# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_auto_20170820_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo_individual',
            name='numero_participantes_disponibles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
