# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_torneo_individual_numero_participantes_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo_individual',
            name='id_torneo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
