# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_auto_20170820_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo_individual',
            name='ganador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
