# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0006_auto_20170820_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo_individual',
            name='ganador',
            field=models.CharField(default='No hay', max_length=50),
        ),
    ]
