# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ygoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duelista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_into_the_vrains', models.BooleanField(default=False, verbose_name='esta_conectado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ygoapp.Usuario')),
            ],
            options={
                'db_table': 'jugador',
            },
        ),
    ]
