# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneo_grupal', '0001_initial'),
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Grupal',
            fields=[
                ('id_ficha', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jugador1', models.CharField(max_length=40)),
                ('deck1', models.CharField(choices=[('zoodiac', 'zoodiac'), ('trueDraco', 'trueDraco'), ('trueDino', 'trueDino'), ('inovked', 'invoked'), ('infernoid', 'infernoid'), ('abc', 'abc'), ('otros', 'otros')], default='otros', max_length=30)),
                ('jugador2', models.CharField(max_length=40)),
                ('deck2', models.CharField(choices=[('zoodiac', 'zoodiac'), ('trueDraco', 'trueDraco'), ('trueDino', 'trueDino'), ('inovked', 'invoked'), ('infernoid', 'infernoid'), ('abc', 'abc'), ('otros', 'otros')], default='otros', max_length=30)),
                ('jugador3', models.CharField(max_length=40, null=True)),
                ('deck3', models.CharField(choices=[('zoodiac', 'zoodiac'), ('trueDraco', 'trueDraco'), ('trueDino', 'trueDino'), ('inovked', 'invoked'), ('infernoid', 'infernoid'), ('abc', 'abc'), ('otros', 'otros')], default='otros', max_length=30, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.Grupo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo_grupal.Torneo_Grupal')),
            ],
            options={
                'db_table': 'ficha_grupal',
            },
        ),
    ]
