# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_grupal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_grupal',
            name='deck3',
            field=models.CharField(choices=[('zoodiac', 'zoodiac'), ('trueDraco', 'trueDraco'), ('trueDino', 'trueDino'), ('inovked', 'invoked'), ('infernoid', 'infernoid'), ('abc', 'abc'), ('otros', 'otros')], default='otros', max_length=30),
        ),
        migrations.AlterField(
            model_name='ficha_grupal',
            name='id_ficha',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ficha_grupal',
            name='jugador3',
            field=models.CharField(default='some', max_length=40),
            preserve_default=False,
        ),
    ]
