# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Individual',
            fields=[
                ('id_ficha', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('deck', models.CharField(choices=[('zoodiac', 'zoodiac'), ('trueDraco', 'trueDraco'), ('trueDino', 'trueDino'), ('inovked', 'invoked'), ('infernoid', 'infernoid'), ('abc', 'abc'), ('otros', 'otros')], default='otros', max_length=30)),
                ('duelista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugador.Duelista')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.Torneo_Individual')),
            ],
            options={
                'db_table': 'ficha_individual',
            },
        ),
    ]
