# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_individual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_individual',
            name='id_ficha',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
