# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('administrador', 'administrador'), ('moderador', 'moderador'), ('jugador', 'jugador')], default='jugador', max_length=30)),
                ('es_personal', models.BooleanField(default=False, verbose_name='es_personal')),
                ('estado', models.CharField(default='C', max_length=1)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(db_column='first_name', max_length=30)),
                ('apellido', models.CharField(db_column='last_name', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(blank=True, default='usuario/noimagen.jpg', help_text='Foto', null=True, upload_to='usuario/')),
                ('ranking', models.CharField(choices=[('novato', 'novato'), ('intermedio', 'intermedio'), ('experto', 'experto'), ('moderador', 'moderador'), ('administrador', 'administrador')], default='novato', max_length=50)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ygoapp.Rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
