# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
