# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_auto_20170902_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='descripcion',
            field=models.TextField(max_length=999),
        ),
    ]
