# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_auto_20170902_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
