# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_auto_20170902_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
