# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_grupal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo_grupal',
            old_name='ganador',
            new_name='grupo_ganador',
        ),
        migrations.RenameField(
            model_name='torneo_grupal',
            old_name='participantes_por_grupo',
            new_name='numero_participantes_disponibles',
        ),
        migrations.AlterField(
            model_name='torneo_grupal',
            name='id_torneo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
