# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo_grupal', '0002_auto_20170820_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo_grupal',
            name='grupo_ganador',
            field=models.CharField(default='No hay', max_length=50),
        ),
    ]
